#!/usr/bin/env bash
# A script that configures my Nginx server so that /redirect_me
# is redirecting to another page

#update package
sudo apt update

#install Nginx
sudo apt install -y nginx

sudo tee /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen       80;
    server_name  localhost;

    location /redirect_me {
        return 301 http://www.youtube.com/;
   }
    include /etc/nginx/sites-available/default;
}
EOF

sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

sudo nginx -t
service nginx restart
