#!/usr/bin/env bash
# A script that automates listening on port 80

rm -f /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default/ /etc/nginx/sites-enabled/default
service nginx restart
