#!/usr/bin/env bash
# A script that accepts one command and runs the whoami
# command under the user passed as an argument

if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi
sudo -u "$1" whoami
