#!/usr/bin/env bash
# A bash script that runs nginx as the nginx user

if pgrep -x "nginx" >/dev/null; then
    echo "nginx is already running ..."
else
    sudo -u nginx nginx -g "daemon off;" &   # start nginx
fi

#configuration settings
sed -i 's/user\s*[^;]*;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen\s*[^;]*;/listen *:8080;/g' /etc/nginx/sites-available/default

sudo nginx -s reload # restart nginx
